# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
# markdown: redcarpet
markdown: kramdown
# highlighter: pygments
highlighter: rouge
permalink: /:year/:month/:day/:title 

exclude: [".rbenv-version", "README.md", "Rakefile"]
auto: true
# pygments: true
# markdown: rdiscount

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : Qian's Blog
tagline: "ninjadq"
author :
  name : Qian Deng
  email : dengqian0826@gmail.com
  github : ninjadq
  twitter : dqbeta

# Theme settings
theme:
  # Google analytics UID
  google_analytics_uid: UA-214442-5
  # Disqus shortname, for comments
  disqus_shortname: ninjadq
  # Number of featured posts on homepage
  homepage_featured: 1
  # Number of posts on homepage (in addition to featured posts)
  homepage_posts: 3
  # Number of words to display in post summaries
  featured_wordcount: 120

# The production_url is only used when full-domain names are needed
# such as sitemap.txt 
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.com, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : http://ninjadq.com

markdown: redcarpet
redcarpet:
  extensions: ["fenced_code_blocks"]